language: node_js
node_js:
  - "10.14.2"

services:
  - postgresql

cache:
  directories: 
    - "node_modules"
before_install:
  - "npm install"
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
test:
  adapter: postgresql
  database: travis_ci_test 

after_success:
  - "npm run coverage"
script:
  - "npm run test"