language: node_js
node_js:
  - "10.14.2"
env:
  - NODE_ENV=test
services:
  - postgresql
cache:
  directories: 
    - "node_modules"
before_install:
  - "npm install"
before_script:
  - psql -c 'create database testdb;' -U postgres
after_success:
  - "npm run coverage"
script:
  - "npm run test"