language: node_js
sudo: false
node_js:
  - 'node'
  - 10
  - 9
  - 8
  - 7
  - 6
matrix:
  include:
  - env: TEST_NODE_VERSION=10
  - env: TEST_NODE_VERSION=9
  - env: TEST_NODE_VERSION=8
  - env: TEST_NODE_VERSION=7
  - env: TEST_NODE_VERSION=6
  - env: TEST_NODE_VERSION=node
before_install:
# Install the Node version to test against
- nvm install $TEST_NODE_VERSION
# Switch back to build-time Node version
- nvm use $TRAVIS_NODE_VERSION
before_script:
- make build-node
- nvm use $TEST_NODE_VERSION
- node --version
- rm -rf ./node_modules package-lock.json
- npm install
script:
  - npm test
branches:
  only:
  - master